[build]
command = "hugo --gc --minify --theme=hugo-swiper"
publish = "public"

[context.production.environment]
HUGO_ENABLEGITINFO = "true"
HUGO_ENV = "production"
HUGO_VERSION = "0.135.0"
NODE_VERSION = "v20.18.0"
NPM_VERSION = "9.6.5"

[context.split1]
command = "hugo mod tidy && hugo mod npm pack && npm install && hugo --gc --minify --theme=hugo-swiper --enableGitInfo"

[context.split1.environment]
HUGO_ENV = "production"
HUGO_VERSION = "0.135.0"
NODE_VERSION = "v20.18.0"
NPM_VERSION = "9.6.5"

[context.deploy-preview]
command = "hugo mod tidy && hugo mod npm pack && npm install && hugo --gc --minify --theme=hugo-swiper --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.135.0"
NODE_VERSION = "v20.18.0"
NPM_VERSION = "9.6.5"

[context.branch-deploy]
command = "hugo mod tidy && hugo mod npm pack && npm install && hugo --gc --minify --theme=hugo-swiper -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.135.0"
NODE_VERSION = "v20.18.0"
NPM_VERSION = "9.6.5"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
